/hst:hst/hst:configurations/myhippoproject/hst:workspace/hst:containers/productlist/main/productlist:
  jcr:primaryType: hst:containeritemcomponent
  hst:componentclassname: org.example.components.ProductListComponent
  hst:iconpath: images/catalog-component-icons/product-list.png
  hst:label: Product List
  hst:template: productlist-main
  hst:xtype: hst.item
