definitions:
  config:
    /hippo:namespaces/myhippoproject/product:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 2d5cac04-f176-49c3-b4dd-7d8d25272050
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: dfc1a79c-59da-4d0b-ae76-3c20b0d69fad
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 60312b29-4671-4620-b72e-eafc7feb8e3f
          hipposysedit:node: true
          hipposysedit:supertype: ['myhippoproject:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/myhippoproject/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /price:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:price
            hipposysedit:primary: false
            hipposysedit:type: Double
          /rating:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:rating
            hipposysedit:primary: false
            hipposysedit:type: Double
          /instock:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:instock
            hipposysedit:primary: false
            hipposysedit:type: Long
          /categories:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: myhippoproject:categories
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myhippoproject:product
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          myhippoproject:title: ''
          myhippoproject:introduction: ''
          myhippoproject:price: 0.0
          myhippoproject:rating: 0.0
          myhippoproject:instock: 0
          jcr:uuid: 6aa66a5c-fb26-4bd8-800a-5043582ffa74
          hippostdpubwf:lastModificationDate: 2018-11-07T15:08:33.214+01:00
          hippostdpubwf:creationDate: 2018-11-07T15:08:33.214+01:00
          myhippoproject:categories: []
          /myhippoproject:description:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            caption: Introduction
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: Description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /price:
            jcr:primaryType: frontend:plugin
            caption: Price
            field: price
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /rating:
            jcr:primaryType: frontend:plugin
            caption: Rating
            field: rating
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /instock:
            jcr:primaryType: frontend:plugin
            caption: In Stock
            field: instock
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /categories:
            jcr:primaryType: frontend:plugin
            caption: Categories
            field: categories
            multiselect.type: checkboxes
            palette.alloworder: false
            palette.maxrows: '10'
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '10'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/myhippoproject/configuration/categories
