/content/documents/myhippoproject/productfacets:
  jcr:primaryType: hippofacnav:facetnavigation
  hippo:docbase: 414a5ff7-6efb-4fe0-8ed6-0c3d939ac442
  hippofacnav:facetnodenames: [Category, Price, Score]
  hippofacnav:facets: ['myhippoproject:categories', 'myhippoproject:price$[{name:''$
      0 - $ 25'', resolution:''double'', end:25}, {name:''$ 25 - $ 50'', resolution:''double'',
      begin:25, end:50}, {name:''$ 50 - $ 100'', resolution:''double'', begin:50,
      end:100}, {name:''$ 100 - $ 250'', resolution:''double'', begin:100, end:250},
      {name:''$ 250 - $ 500'', resolution:''double'', begin:250, end:500}, {name:''$
      500 and more'', resolution:''double'', begin:500}]', 'myhippoproject:rating$[{name:''1
      star or more'', resolution:''double'', begin:1}, {name:''2 stars or more'',
      resolution:''double'', begin:2}, {name:''3 stars or more'', resolution:''double'',
      begin:3}, {name:''4 stars or more'', resolution:''double'', begin:4}, {name:''5
      stars'', resolution:''double'', begin:5, end:6}]']
  hippofacnav:filters: ['jcr:primaryType=myhippoproject:product']
