definitions:
  config:
    /hst:hst/hst:configurations/myhippoproject/hst:pages/productpage:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:componentclassname: org.example.components.ProductComponent
        hst:template: productpage-main
